name: manager_mobile

description: "Flutter application for managing evaluations, with support for photos, synchronization, and offline usage."

publish_to: 'none'

version: 1.1.9+14

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  get_it: ^9.1.0
  path_provider: ^2.1.5  
  validatorless: ^1.2.4
  connectivity_plus: ^7.0.0
  path: ^1.9.1
  animated_toggle_switch: ^0.8.4
  top_snackbar_flutter: ^3.1.0
  cloud_firestore: ^6.0.3
  uuid: ^4.5.1
  firebase_storage: ^13.0.3
  intl: ^0.20.2
  signature: ^6.3.0
  flutter_localizations:
    sdk: flutter
  image: ^4.5.2  
  avatar_glow: ^3.0.1  
  wakelock_plus: ^1.4.0  
  lottie: ^3.3.2
  timezone: ^0.10.1
  http: ^1.6.0
  image_picker: ^1.2.2
  sqflite: ^2.4.2+1
  package_info_plus: ^10.1.0 
  
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.4+4
  fake_cloud_firestore: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/json/sync_animation.json
    - assets/json/upload_animation.json
    - assets/images/app_icon.png